name: ButtonPromote
main: me.iMint.ButtonPromote.ButtonPromote
version: 2.0
author: iMint, furt
depend: [Vault]
database: true
commands:
    bp:
        description: Main command.
        usage: /bp
            