name: ${project.name}
main: ${main.class}
version: ${project.version}
authors: [furt, _InnoKo_]
description: >
             ${project.name} takes the common button and pressure plate and extends on them. 
depend: [Vault]
database: true
commands:
    buttonpromote:
      aliases:
        - bp
        - bpromote
      description: Main command.
      usage: /<command>
            